#!/bin/sh
query=$(printf  "%s" "$*" | tr ' ' '+')
mpv --no-terminal --no-video "https://youtube.com/$(curl -s "https://vid.puffyan.us/search?q=$query" | grep -Eo "/watch\?v=.{11}" | head -n 1 )" & cava
